# Generated by Django 4.2.7 on 2025-08-07 17:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم العام الدراسي')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'العام الدراسي',
                'verbose_name_plural': 'السنوات الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الإدارة')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='رمز الإدارة')),
            ],
            options={
                'verbose_name': 'الإدارة',
                'verbose_name_plural': 'الإدارات',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ النهاية')),
                ('location', models.CharField(max_length=200, verbose_name='الموقع')),
                ('image', models.ImageField(blank=True, upload_to='events/', verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'الفعالية',
                'verbose_name_plural': 'الفعاليات',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('url', models.URLField(verbose_name='الرابط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'الرابط الخارجي',
                'verbose_name_plural': 'الروابط الخارجية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المعهد')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='رمز المعهد')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_management.department', verbose_name='الإدارة')),
            ],
            options={
                'verbose_name': 'المعهد',
                'verbose_name_plural': 'المعاهد',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
            ],
            options={
                'verbose_name': 'الخبر',
                'verbose_name_plural': 'الأخبار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المنطقة')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='رمز المنطقة')),
            ],
            options={
                'verbose_name': 'المنطقة',
                'verbose_name_plural': 'المناطق',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الطالب')),
                ('national_id', models.CharField(max_length=14, unique=True, verbose_name='الرقم القومي')),
                ('gender', models.CharField(choices=[('male', 'بنين'), ('female', 'فتيات')], max_length=6, verbose_name='النوع')),
                ('education_level', models.CharField(choices=[('primary', 'ابتدائي'), ('middle', 'إعدادي'), ('secondary', 'ثانوي')], max_length=10, verbose_name='المرحلة التعليمية')),
                ('grade', models.CharField(max_length=20, verbose_name='الصف')),
                ('personal_photo', models.ImageField(upload_to='students/photos/', verbose_name='الصورة الشخصية')),
                ('birth_certificate', models.ImageField(upload_to='students/documents/', verbose_name='شهادة الميلاد/البطاقة')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="رقم الهاتف يجب أن يكون بالصيغة: '+999999999'. يسمح حتى 15 رقم.", regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_management.academicyear', verbose_name='العام الدراسي')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_management.institute', verbose_name='المعهد')),
            ],
            options={
                'verbose_name': 'الطالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الاختبار')),
                ('description', models.TextField(verbose_name='وصف الاختبار')),
                ('education_level', models.CharField(choices=[('primary', 'ابتدائي'), ('middle', 'إعدادي'), ('secondary', 'ثانوي')], max_length=10, verbose_name='المرحلة التعليمية')),
                ('gender', models.CharField(choices=[('male', 'بنين'), ('female', 'فتيات')], max_length=6, verbose_name='النوع')),
                ('max_score', models.IntegerField(verbose_name='الدرجة القصوى')),
            ],
            options={
                'verbose_name': 'الاختبار',
                'verbose_name_plural': 'الاختبارات',
            },
        ),
        migrations.CreateModel(
            name='TrainingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('education_level', models.CharField(choices=[('primary', 'ابتدائي'), ('middle', 'إعدادي'), ('secondary', 'ثانوي')], max_length=10, verbose_name='المرحلة التعليمية')),
                ('file', models.FileField(blank=True, upload_to='training/', verbose_name='الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'الوحدة التدريبية',
                'verbose_name_plural': 'الوحدات التدريبية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('video_url', models.URLField(verbose_name='رابط الفيديو')),
                ('category', models.CharField(max_length=50, verbose_name='الفئة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'الفيديو',
                'verbose_name_plural': 'الفيديوهات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_management.region', verbose_name='المنطقة'),
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الدرجة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('test_date', models.DateField(verbose_name='تاريخ الاختبار')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_management.student', verbose_name='الطالب')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_management.test', verbose_name='الاختبار')),
            ],
            options={
                'verbose_name': 'اختبار الطالب',
                'verbose_name_plural': 'اختبارات الطلاب',
                'unique_together': {('student', 'test')},
            },
        ),
    ]
